# Generated by Django 3.0.4 on 2020-03-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='logoinfo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logomaker.category')),
            ],
        ),
    ]
