# Generated by Django 3.0.4 on 2020-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logoid',
            field=models.IntegerField(default=0),
        ),
    ]
