# Generated by Django 3.0.4 on 2020-03-20 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0005_client_logoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='datetime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='client',
            name='logoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logomaker.logoinfo'),
        ),
    ]
