# Generated by Django 3.0.4 on 2020-03-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0007_client_mark_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logoinfo', to='logomaker.logoinfo'),
        ),
    ]
