# Generated by Django 3.0.4 on 2020-03-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0008_auto_20200323_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='logomaker.logoinfo'),
        ),
    ]
