# Generated by Django 3.0.4 on 2020-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0010_auto_20200323_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.TextField(default='0')),
            ],
        ),
    ]
